#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# Cache infra values (droplet IP, domain) here — not the app's real .env.
ENV_FILE="deploy/.wizard-state"

TOTAL_STAGES=8

banner "Provision DigitalOcean droplet — hanson-landscape preview deploy"

# ── Stage 1: SSH key ───────────────────────────────────────────────────────
stage "Local SSH key"
say "DigitalOcean droplets are created with an SSH public key attached."
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
  note "Found existing key: ~/.ssh/id_ed25519.pub"
  PUBKEY=$(cat "$HOME/.ssh/id_ed25519.pub")
else
  warn "No ~/.ssh/id_ed25519.pub found."
  if confirm "Generate one now (ssh-keygen -t ed25519)?"; then
    ssh-keygen -t ed25519 -C "hanson-landscape-droplet" -f "$HOME/.ssh/id_ed25519"
    PUBKEY=$(cat "$HOME/.ssh/id_ed25519.pub")
  else
    ask PUBKEY_PATH "Path to your existing public key:"
    PUBKEY=$(cat "$PUBKEY_PATH")
  fi
fi
say "Your public key (you'll paste this into DigitalOcean in the next stage):"
printf '\n  %s\n\n' "$PUBKEY"
pause "Copied it? Press Enter to continue."

# ── Stage 2: create the droplet ────────────────────────────────────────────
stage "Create the droplet"
say "Create a small Ubuntu droplet — plenty for a client-preview site."
open_url "https://cloud.digitalocean.com/droplets/new"
step "Image: Ubuntu 24.04 LTS"
step "Plan: Basic → Regular → \$6/mo (1 GB RAM) is enough for preview traffic"
step "Authentication: SSH Key → New SSH Key → paste the key from Stage 1"
step "Hostname: e.g. hanson-landscape-preview"
step "Create Droplet, wait for it to boot, then copy its public IPv4 address"
ask DROPLET_IP "Droplet public IP:"
write_env DROPLET_IP "$DROPLET_IP"

# ── Stage 3: confirm SSH access ────────────────────────────────────────────
stage "Confirm SSH access"
say "Testing SSH into the droplet as root (DigitalOcean's default user)."
until ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=8 "root@$DROPLET_IP" 'echo connected' 2>/dev/null; do
  warn "Couldn't connect yet — droplet may still be booting."
  confirm "Retry?" || break
done
say "SSH access confirmed."
pause

# ── Stage 4: server bootstrap ───────────────────────────────────────────────
stage "Install Node, Nginx, PM2, certbot"
say "Running the one-time server setup over SSH (matches .nvmrc: Node 22)."
confirm "Run bootstrap commands on $DROPLET_IP now?" && ssh "root@$DROPLET_IP" bash -s <<'REMOTE'
set -euo pipefail
apt-get update -y
apt-get install -y curl git nginx certbot python3-certbot-nginx ufw
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs
npm i -g pm2
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable
node -v
REMOTE
say "Node, Nginx, PM2, certbot installed."
pause

# ── Stage 5: GitHub deploy key + clone ──────────────────────────────────────
stage "Clone the repo (private — needs a deploy key)"
say "Repo is git@github.com:blakelyons/hanson-landscape-next-js.git (private)."
say "Generating a deploy-only SSH key ON THE DROPLET, so your personal key never leaves your laptop."
ssh "root@$DROPLET_IP" '[[ -f ~/.ssh/id_ed25519 ]] || ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519 -C "hanson-landscape-droplet-deploy-key"'
DEPLOY_PUBKEY=$(ssh "root@$DROPLET_IP" 'cat ~/.ssh/id_ed25519.pub')
say "Droplet's deploy public key:"
printf '\n  %s\n\n' "$DEPLOY_PUBKEY"
open_url "https://github.com/blakelyons/hanson-landscape-next-js/settings/keys/new"
step "Title: droplet-deploy-key"
step "Paste the key above"
step "Leave 'Allow write access' UNCHECKED (read-only is enough)"
step "Add key"
pause "Added it? Press Enter to continue."
confirm "Clone the repo onto the droplet now?" && ssh "root@$DROPLET_IP" bash -s <<'REMOTE'
set -euo pipefail
ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2>/dev/null
[[ -d /var/www/hanson-landscape ]] || git clone git@github.com:blakelyons/hanson-landscape-next-js.git /var/www/hanson-landscape
REMOTE
say "Repo cloned to /var/www/hanson-landscape."
pause

# ── Stage 6: env vars + first build + pm2 ──────────────────────────────────
stage "Server env vars, first build, PM2 start"
say "These populate .env.production on the droplet (per .env.example) — never stored locally."
ask SITE_URL_REMOTE "NEXT_PUBLIC_SITE_URL (e.g. https://preview.hansonlandscape.com):"
ssh "root@$DROPLET_IP" bash -s <<REMOTE
set -euo pipefail
cd /var/www/hanson-landscape
cat > .env.production <<ENVEOF
NEXT_PUBLIC_SITE_URL=${SITE_URL_REMOTE}
ENVEOF
npm ci
npm run build
pm2 start ecosystem.config.js
pm2 save
REMOTE
say "App built and running under PM2 on port 3000."
step "Run the 'pm2 startup' command it prints below on the droplet so it survives a reboot:"
ssh "root@$DROPLET_IP" 'pm2 startup systemd -u root --hp /root' || true
pause "Run the printed command on the droplet (copy/paste over SSH), then press Enter."

# ── Stage 7: DNS + Nginx ────────────────────────────────────────────────────
stage "Point a subdomain at the droplet + configure Nginx"
ask PREVIEW_DOMAIN "Subdomain for client preview (e.g. preview.hansonlandscape.com):"
write_env PREVIEW_DOMAIN "$PREVIEW_DOMAIN"
say "Add an A record at your DNS provider for hansonlandscape.com:"
step "Type: A, Host: ${PREVIEW_DOMAIN%%.*}, Value: $DROPLET_IP, TTL: default"
note "If DNS is on DigitalOcean, use https://cloud.digitalocean.com/networking/domains"
pause "Added the A record? Press Enter to continue (propagation can take a few minutes)."
ssh "root@$DROPLET_IP" bash -s <<REMOTE
set -euo pipefail
cat > /etc/nginx/sites-available/${PREVIEW_DOMAIN} <<'NGINXEOF'
server {
    listen 80;
    server_name ${PREVIEW_DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGINXEOF
ln -sf /etc/nginx/sites-available/${PREVIEW_DOMAIN} /etc/nginx/sites-enabled/${PREVIEW_DOMAIN}
nginx -t
systemctl reload nginx
REMOTE
say "Nginx reverse proxy configured for $PREVIEW_DOMAIN → :3000."
pause

# ── Stage 8: TLS ────────────────────────────────────────────────────────────
stage "TLS via Let's Encrypt"
ask CERTBOT_EMAIL "Email for Let's Encrypt renewal notices:"
confirm "Run certbot for $PREVIEW_DOMAIN now (DNS must have propagated)?" && \
  ssh "root@$DROPLET_IP" "certbot --nginx -d '$PREVIEW_DOMAIN' -m '$CERTBOT_EMAIL' --agree-tos --redirect -n"
say "Visit https://$PREVIEW_DOMAIN to confirm it's live."
pause

finish
note "Redeploys: ssh root@$DROPLET_IP, cd /var/www/hanson-landscape, then bash deploy/deploy.sh"
