// Extracts only the icons this repo actually uses out of the full Iconify
// collections and writes a small static module. This lets <Icon> render the
// SVG synchronously on first paint instead of fetching from api.iconify.design
// at runtime (which caused the "start your project" button icon to pop in
// late and shift the layout).
//
// Run `npm run generate:icons` after adding a new `icon="prefix:name"` usage.

import { writeFileSync, readFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { getIconData } from "@iconify/utils";

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(rootDir, "..");
const srcDir = path.join(repoRoot, "src");

const collectionsByPrefix = {
    lucide: () => import("@iconify-json/lucide/icons.json", { with: { type: "json" } }),
    ci: () => import("@iconify-json/ci/icons.json", { with: { type: "json" } }),
    "line-md": () => import("@iconify-json/line-md/icons.json", { with: { type: "json" } }),
    mingcute: () => import("@iconify-json/mingcute/icons.json", { with: { type: "json" } }),
    "streamline-ultimate": () => import("@iconify-json/streamline-ultimate/icons.json", { with: { type: "json" } }),
};

const knownPrefixes = Object.keys(collectionsByPrefix).join("|");
const iconUsageRegex = new RegExp(`["'](${knownPrefixes}):([a-z0-9-]+)["']`, "g");

function collectFiles(dir, files = []) {
    for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry);
        const stat = statSync(full);
        if (stat.isDirectory()) {
            if (entry === "node_modules" || entry === ".next") continue;
            collectFiles(full, files);
        } else if (/\.(tsx|ts|jsx|js)$/.test(entry) && !entry.endsWith(".test.tsx") && !entry.endsWith(".test.ts")) {
            files.push(full);
        }
    }
    return files;
}

const usedIcons = new Set();
for (const file of collectFiles(srcDir)) {
    const content = readFileSync(file, "utf8");
    for (const match of content.matchAll(iconUsageRegex)) {
        usedIcons.add(`${match[1]}:${match[2]}`);
    }
}

const output = {};
for (const iconRef of [...usedIcons].sort()) {
    const [prefix, name] = iconRef.split(":");
    const loader = collectionsByPrefix[prefix];
    if (!loader) {
        throw new Error(`No local icon collection registered for prefix "${prefix}" (used as "${iconRef}")`);
    }
    const { default: iconSet } = await loader();
    const data = getIconData(iconSet, name);
    if (!data) {
        throw new Error(`Icon "${iconRef}" not found in @iconify-json/${prefix}`);
    }
    output[iconRef] = data;
}

const outPath = path.join(repoRoot, "src/components/ui/icons.generated.ts");
const banner = `// Auto-generated by scripts/generate-icons.mjs — do not edit by hand.\n// Re-run \`npm run generate:icons\` after adding a new icon="prefix:name" usage.\n`;
const body = `import type { IconifyIcon } from "@iconify/react";\n\nexport const generatedIcons: Record<string, IconifyIcon> = ${JSON.stringify(output, null, 4)};\n`;
writeFileSync(outPath, banner + body);

console.log(`Wrote ${Object.keys(output).length} icon(s) to ${path.relative(repoRoot, outPath)}`);
