// One-off dev script — not part of the shipped runtime bundle.
// Run with: node --experimental-strip-types scripts/generate-leaf-base-points.ts
//
// Reads the tree SVG's 110 leaf paths (Vector..Vector_110) and the trunk/branch
// path ("Branches") out of large-tree-svg.tsx, computes each leaf's base point
// via the shared geometry function, and writes the committed dataset consumed
// at runtime by LargeTreeSvg.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeLeafBasePoint } from "../src/components/ui/large-tree-svg.logic.ts";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const svgSourcePath = path.resolve(dirname, "../src/components/ui/large-tree-svg.tsx");
const outputPath = path.resolve(dirname, "../src/components/ui/leaf-base-points.ts");

function extractPathD(source: string, id: string): string {
    const pattern = new RegExp(`id="${id}"[^>]*?\\sd="([^"]+)"`, "s");
    const match = source.match(pattern);
    if (!match) {
        throw new Error(`Could not find a path with id="${id}" in ${svgSourcePath}`);
    }
    return match[1];
}

const source = readFileSync(svgSourcePath, "utf-8");
const trunkPathD = extractPathD(source, "Branches");

const leafIds = ["Vector", ...Array.from({ length: 109 }, (_, i) => `Vector_${i + 2}`)];

const basePoints = leafIds.map((id) => {
    const leafPathD = extractPathD(source, id);
    const { x, y } = computeLeafBasePoint(leafPathD, trunkPathD);
    return { id, x: Math.round(x * 100) / 100, y: Math.round(y * 100) / 100 };
});

const output = `// Generated by scripts/generate-leaf-base-points.ts — do not hand-edit.
// Per-leaf attachment point ({id, x, y} in the tree SVG's own coordinate space),
// used to set each leaf's transform-origin and dot/leaf default-state markup.

export type LeafBasePoint = { id: string; x: number; y: number };

export const LEAF_BASE_POINTS: LeafBasePoint[] = ${JSON.stringify(basePoints, null, 4)};
`;

writeFileSync(outputPath, output);
console.log(`Wrote ${basePoints.length} leaf base points to ${outputPath}`);
