// Generated by scripts/generate-leaf-base-points.ts — do not hand-edit.
// Per-leaf attachment point ({id, x, y} in the tree SVG's own coordinate space),
// used to set each leaf's transform-origin and dot/leaf default-state markup.

export type LeafBasePoint = { id: string; x: number; y: number };

export const LEAF_BASE_POINTS: LeafBasePoint[] = [
    {
        id: "Vector",
        x: 300.11,
        y: 618.56,
    },
    {
        id: "Vector_2",
        x: 317.85,
        y: 635.41,
    },
    {
        id: "Vector_3",
        x: 321.46,
        y: 609.76,
    },
    {
        id: "Vector_4",
        x: 342,
        y: 628.71,
    },
    {
        id: "Vector_5",
        x: 392.01,
        y: 619.04,
    },
    {
        id: "Vector_6",
        x: 393.12,
        y: 619,
    },
    {
        id: "Vector_7",
        x: 329.17,
        y: 562.77,
    },
    {
        id: "Vector_8",
        x: 227.78,
        y: 448.34,
    },
    {
        id: "Vector_9",
        x: 249.91,
        y: 435.09,
    },
    {
        id: "Vector_10",
        x: 262.88,
        y: 511.02,
    },
    {
        id: "Vector_11",
        x: 262.83,
        y: 488.41,
    },
    {
        id: "Vector_12",
        x: 282.2,
        y: 446.9,
    },
    {
        id: "Vector_13",
        x: 228.15,
        y: 324.49,
    },
    {
        id: "Vector_14",
        x: 335.98,
        y: 410.22,
    },
    {
        id: "Vector_15",
        x: 349.58,
        y: 460.91,
    },
    {
        id: "Vector_16",
        x: 308.73,
        y: 492.46,
    },
    {
        id: "Vector_17",
        x: 348.61,
        y: 477.64,
    },
    {
        id: "Vector_18",
        x: 353.19,
        y: 405.11,
    },
    {
        id: "Vector_19",
        x: 372.72,
        y: 422.06,
    },
    {
        id: "Vector_20",
        x: 409.65,
        y: 412.91,
    },
    {
        id: "Vector_21",
        x: 404.19,
        y: 483.45,
    },
    {
        id: "Vector_22",
        x: 234.35,
        y: 346.82,
    },
    {
        id: "Vector_23",
        x: 259.5,
        y: 358.04,
    },
    {
        id: "Vector_24",
        x: 230.78,
        y: 322.48,
    },
    {
        id: "Vector_25",
        x: 275.5,
        y: 263.69,
    },
    {
        id: "Vector_26",
        x: 267.04,
        y: 312.53,
    },
    {
        id: "Vector_27",
        x: 287.69,
        y: 306.9,
    },
    {
        id: "Vector_28",
        x: 306.81,
        y: 357.64,
    },
    {
        id: "Vector_29",
        x: 275.93,
        y: 262.64,
    },
    {
        id: "Vector_30",
        x: 280.29,
        y: 214.09,
    },
    {
        id: "Vector_31",
        x: 311.75,
        y: 328.56,
    },
    {
        id: "Vector_32",
        x: 255.11,
        y: 191.19,
    },
    {
        id: "Vector_33",
        x: 279.91,
        y: 184.49,
    },
    {
        id: "Vector_34",
        x: 307.71,
        y: 207.96,
    },
    {
        id: "Vector_35",
        x: 259.01,
        y: 195.53,
    },
    {
        id: "Vector_36",
        x: 355.51,
        y: 246.55,
    },
    {
        id: "Vector_37",
        x: 369.4,
        y: 251.43,
    },
    {
        id: "Vector_38",
        x: 316.9,
        y: 252.8,
    },
    {
        id: "Vector_39",
        x: 360.65,
        y: 302.11,
    },
    {
        id: "Vector_40",
        x: 370.3,
        y: 88.24,
    },
    {
        id: "Vector_41",
        x: 351.88,
        y: 108.35,
    },
    {
        id: "Vector_42",
        x: 376.89,
        y: 113.46,
    },
    {
        id: "Vector_43",
        x: 354.02,
        y: 137.03,
    },
    {
        id: "Vector_44",
        x: 351.55,
        y: 195.36,
    },
    {
        id: "Vector_45",
        x: 355.1,
        y: 185.19,
    },
    {
        id: "Vector_46",
        x: 363.24,
        y: 185.5,
    },
    {
        id: "Vector_47",
        x: 412.29,
        y: 135.68,
    },
    {
        id: "Vector_48",
        x: 397.18,
        y: 136.29,
    },
    {
        id: "Vector_49",
        x: 393.74,
        y: 129.65,
    },
    {
        id: "Vector_50",
        x: 326.69,
        y: 346.04,
    },
    {
        id: "Vector_51",
        x: 352.95,
        y: 307.61,
    },
    {
        id: "Vector_52",
        x: 471.96,
        y: 148.04,
    },
    {
        id: "Vector_53",
        x: 443.98,
        y: 149.84,
    },
    {
        id: "Vector_54",
        x: 425.59,
        y: 167.25,
    },
    {
        id: "Vector_55",
        x: 472.2,
        y: 163.57,
    },
    {
        id: "Vector_56",
        x: 517.97,
        y: 182.51,
    },
    {
        id: "Vector_57",
        x: 500.27,
        y: 177.59,
    },
    {
        id: "Vector_58",
        x: 458.79,
        y: 175.25,
    },
    {
        id: "Vector_59",
        x: 480,
        y: 194.78,
    },
    {
        id: "Vector_60",
        x: 436.77,
        y: 196.32,
    },
    {
        id: "Vector_61",
        x: 427.28,
        y: 189.37,
    },
    {
        id: "Vector_62",
        x: 433.57,
        y: 140.63,
    },
    {
        id: "Vector_63",
        x: 436.34,
        y: 226.15,
    },
    {
        id: "Vector_64",
        x: 466.25,
        y: 238.04,
    },
    {
        id: "Vector_65",
        x: 443.87,
        y: 238.07,
    },
    {
        id: "Vector_66",
        x: 428.84,
        y: 273.51,
    },
    {
        id: "Vector_67",
        x: 505.56,
        y: 235.13,
    },
    {
        id: "Vector_68",
        x: 500.1,
        y: 199.24,
    },
    {
        id: "Vector_69",
        x: 464.15,
        y: 247.85,
    },
    {
        id: "Vector_70",
        x: 569.34,
        y: 243.38,
    },
    {
        id: "Vector_71",
        x: 563.67,
        y: 266.92,
    },
    {
        id: "Vector_72",
        x: 514.22,
        y: 261.21,
    },
    {
        id: "Vector_73",
        x: 579.08,
        y: 267.67,
    },
    {
        id: "Vector_74",
        x: 566.64,
        y: 292.13,
    },
    {
        id: "Vector_75",
        x: 479.58,
        y: 286.91,
    },
    {
        id: "Vector_76",
        x: 465.67,
        y: 314.09,
    },
    {
        id: "Vector_77",
        x: 471.29,
        y: 291.64,
    },
    {
        id: "Vector_78",
        x: 480.17,
        y: 302.42,
    },
    {
        id: "Vector_79",
        x: 449.03,
        y: 344.09,
    },
    {
        id: "Vector_80",
        x: 432.89,
        y: 307.52,
    },
    {
        id: "Vector_81",
        x: 546.74,
        y: 334.6,
    },
    {
        id: "Vector_82",
        x: 594.22,
        y: 343.47,
    },
    {
        id: "Vector_83",
        x: 571.83,
        y: 392.39,
    },
    {
        id: "Vector_84",
        x: 525.53,
        y: 336.54,
    },
    {
        id: "Vector_85",
        x: 548.39,
        y: 368.25,
    },
    {
        id: "Vector_86",
        x: 504.4,
        y: 407.12,
    },
    {
        id: "Vector_87",
        x: 504.45,
        y: 368.76,
    },
    {
        id: "Vector_88",
        x: 575.63,
        y: 336.28,
    },
    {
        id: "Vector_89",
        x: 521.97,
        y: 402.89,
    },
    {
        id: "Vector_90",
        x: 658.29,
        y: 408.61,
    },
    {
        id: "Vector_91",
        x: 571.08,
        y: 358.81,
    },
    {
        id: "Vector_92",
        x: 624.12,
        y: 402.54,
    },
    {
        id: "Vector_93",
        x: 645.19,
        y: 422.01,
    },
    {
        id: "Vector_94",
        x: 633.13,
        y: 511.33,
    },
    {
        id: "Vector_95",
        x: 498.71,
        y: 494.58,
    },
    {
        id: "Vector_96",
        x: 516.92,
        y: 484.86,
    },
    {
        id: "Vector_97",
        x: 584.72,
        y: 432.46,
    },
    {
        id: "Vector_98",
        x: 579.22,
        y: 471,
    },
    {
        id: "Vector_99",
        x: 528.22,
        y: 512.34,
    },
    {
        id: "Vector_100",
        x: 509.63,
        y: 566.47,
    },
    {
        id: "Vector_101",
        x: 624.25,
        y: 479.18,
    },
    {
        id: "Vector_102",
        x: 605.36,
        y: 519.41,
    },
    {
        id: "Vector_103",
        x: 605.8,
        y: 650.49,
    },
    {
        id: "Vector_104",
        x: 565.45,
        y: 660.98,
    },
    {
        id: "Vector_105",
        x: 589.6,
        y: 666.76,
    },
    {
        id: "Vector_106",
        x: 578.44,
        y: 594.67,
    },
    {
        id: "Vector_107",
        x: 581.7,
        y: 640.29,
    },
    {
        id: "Vector_108",
        x: 514.94,
        y: 651.62,
    },
    {
        id: "Vector_109",
        x: 512.83,
        y: 650.91,
    },
    {
        id: "Vector_110",
        x: 550.47,
        y: 539.3,
    },
];
